---
title: "NBA Project"
author: "Matthew Grimm"
date: "5/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### packages
library(ggeffects)
library(rstanarm)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stargazer)
library(bayesplot)
library(gridExtra)
library(tidyverse)
library(ggplot2)
library(xtable)
library(naniar)
library(kableExtra)
options(xtable.comment = FALSE)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r, include = FALSE}
# Forwards
bron <- read.csv("~/Downloads/NBA/player_data/bron.csv")
pg <- read.csv("~/Downloads/NBA/player_data/pg.csv")

# Guards
dame <- read.csv("~/Downloads/NBA/player_data/dame.csv")
luka <- read.csv("~/Downloads/NBA/player_data/luka.csv")

# Centers
embiid <- read.csv("~/Downloads/NBA/player_data/embiid.csv")
kat <- read.csv("~/Downloads/NBA/player_data/kat.csv")

```

#### Guard Model

Potential covariates to consider (all lagged)

-   minutes played
-   points
-   WL in last game
-   FG pct or 3pt pct

Potential covariates with no lags

-   opponent
-   age?

```{r}
ggplot(data = dame, aes(x=X, y = PTS)) + geom_point(aes(colour = WL)) + geom_smooth(aes(colour=WL))

```

#### Forward Model

```{r}


```

#### Center Model

```{r}


```
